#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
翻译所有SKILL.md文件为中文
"""
import os
import re
import json

# 翻译映射表 - 核心术语翻译
TRANSLATION_MAP = {
    # 常见标题
    "Overview": "概述",
    "Core Philosophy": "核心理念",
    "Critical": "重要提示",
    "Data Source": "数据源",
    "Key Principles": "核心原则",
    "Best Practices": "最佳实践",
    "Common Mistakes": "常见错误",
    "Workflow": "工作流程",
    "Deliverables": "交付物",
    "Quality Checklist": "质量检查清单",
    "Tools": "工具",
    "Reference": "参考",
    "Examples": "示例",
    "Notes": "注意",
    "Important": "重要",
    "Warning": "警告",

    # 金融术语
    "Comparable Company Analysis": "可比公司分析",
    "DCF (Discounted Cash Flow)": "DCF（折现现金流）",
    "LBO (Leveraged Buyout)": "LBO（杠杆收购）",
    "Three-Statement Model": "三表模型",
    "Income Statement": "利润表",
    "Balance Sheet": "资产负债表",
    "Cash Flow Statement": "现金流量表",
    "Enterprise Value": "企业价值",
    "Market Cap": "市值",
    "EBITDA": "息税折旧摊销前利润",
    "Free Cash Flow": "自由现金流",
    "WACC": "加权平均资本成本",
    "Terminal Value": "终值",
    "Revenue": "收入",
    "Gross Margin": "毛利率",
    "Operating Margin": "营业利润率",
    "Net Income": "净利润",
    "Multiples": "倍数",
    "Valuation": "估值",
    "Projection": "预测",
    "Forecast": "预测",
    "Assumptions": "假设",
    "Sensitivity Analysis": "敏感性分析",
    "Scenario": "情景",
    "Bear Case": "悲观情景",
    "Base Case": "基准情景",
    "Bull Case": "乐观情景",

    # 投行术语
    "M&A": "并购",
    "IPO": "首次公开募股",
    "CIM (Confidential Information Memorandum)": "CIM（保密信息备忘录）",
    "Teaser": "匿名简介",
    "Pitch Deck": "路演材料",
    "Data Pack": "数据包",
    "Buyer List": "买家清单",
    "Process Letter": "流程函",
    "Strip Profile": "公司一页",
    "Merger Model": "并购模型",

    # 私募股权术语
    "Due Diligence": "尽职调查",
    "DD": "尽调",
    "Investment Committee": "投资委员会",
    "IC Memo": "IC备忘录",
    "Portfolio Monitoring": "投后监控",
    "Value Creation": "价值创造",
    "Unit Economics": "单元经济",
    "Returns Analysis": "回报分析",
    "Deal Sourcing": "项目发掘",
    "Deal Screening": "项目筛选",
    "IRR": "内部收益率",
    "MOIC": "投资回报倍数",

    # 财富管理术语
    "Financial Plan": "财务规划",
    "Investment Proposal": "投资提案",
    "Client Report": "客户报告",
    "Rebalancing": "再平衡",
    "Tax Loss Harvesting": "税损收割",
    "Asset Allocation": "资产配置",
    "Risk Tolerance": "风险承受能力",

    # 基金管理术语
    "NAV": "净资产价值",
    "General Ledger": "总账",
    "Reconciliation": "对账",
    "Accrual": "应计",
    "Break": "断点",
    "Variance": "差异",
    "Roll Forward": "滚动结转",

    # KYC术语
    "KYC (Know Your Customer)": "KYC（了解你的客户）",
    "KYC Document Parsing": "KYC文档解析",
    "KYC Rules Engine": "KYC规则引擎",
    "UBO (Ultimate Beneficial Owner)": "UBO（最终受益人）",
    "Sanctions List": "制裁名单",
    "PEP (Politically Exposed Person)": "PEP（政治公众人物）",
    "Compliance": "合规",

    # 通用术语
    "Skill": "技能",
    "Template": "模板",
    "Format": "格式",
    "Output": "输出",
    "Input": "输入",
    "Formula": "公式",
    "Calculation": "计算",
    "Analysis": "分析",
    "Report": "报告",
    "Document": "文档",
    "File": "文件",
    "Sheet": "工作表",
    "Workbook": "工作簿",
    "Excel": "Excel",
    "PowerPoint": "PowerPoint",
    "PPT": "PPT",
    "Model": "模型",
    "Data": "数据",
    "Information": "信息",
    "Source": "来源",
    "Reference": "参考",
    "Step": "步骤",
    "Process": "流程",
    "Method": "方法",
    "Approach": "方法",
    "Technique": "技巧",
    "Strategy": "策略",
    "Guidance": "指导",
    "Instructions": "说明",
    "Requirements": "要求",
    "Constraints": "约束",
    "Considerations": "考虑因素",
    "Best Practice": "最佳实践",
    "Common Error": "常见错误",
    "Pitfall": "陷阱",
    "Tip": "提示",
    "Note": "注意",
    "Important": "重要",
    "Warning": "警告",
    "Critical": "关键",
    "Mandatory": "必须",
    "Required": "必需",
    "Optional": "可选",
    "Recommended": "推荐",
    "Suggested": "建议",
    "Example": "示例",
    "Sample": "样本",
    "Template": "模板",
    "Format": "格式",
    "Structure": "结构",
    "Layout": "布局",
    "Design": "设计",
    "Create": "创建",
    "Build": "构建",
    "Generate": "生成",
    "Produce": "生成",
    "Output": "输出",
    "Deliver": "交付",
    "Provide": "提供",
    "Include": "包括",
    "Contain": "包含",
    "Consist of": "由...组成",
    "Comprise": "包含",
    "Compose": "组成",
    "Add": "添加",
    "Remove": "移除",
    "Update": "更新",
    "Modify": "修改",
    "Change": "更改",
    "Adjust": "调整",
    "Set": "设置",
    "Get": "获取",
    "Fetch": "获取",
    "Retrieve": "检索",
    "Extract": "提取",
    "Parse": "解析",
    "Process": "处理",
    "Handle": "处理",
    "Manage": "管理",
    "Control": "控制",
    "Check": "检查",
    "Verify": "验证",
    "Validate": "验证",
    "Confirm": "确认",
    "Review": "审查",
    "Audit": "审计",
    "Test": "测试",
    "Debug": "调试",
    "Fix": "修复",
    "Solve": "解决",
    "Resolve": "解决",
    "Address": "处理",
    "Complete": "完成",
    "Finish": "完成",
    "Done": "完成",
    "Success": "成功",
    "Failure": "失败",
    "Error": "错误",
    "Issue": "问题",
    "Problem": "问题",
    "Bug": "缺陷",
    "Mistake": "错误",
    "Fault": "故障",
    "Exception": "异常",
    "Warning": "警告",
    "Alert": "提醒",
    "Notification": "通知",
    "Message": "消息",
    "Information": "信息",
    "Data": "数据",
    "Content": "内容",
    "Text": "文本",
    "String": "字符串",
    "Number": "数字",
    "Value": "值",
    "Variable": "变量",
    "Parameter": "参数",
    "Argument": "参数",
    "Function": "函数",
    "Method": "方法",
    "Procedure": "过程",
    "Routine": "例程",
    "Algorithm": "算法",
    "Logic": "逻辑",
    "Condition": "条件",
    "Rule": "规则",
    "Constraint": "约束",
    "Requirement": "要求",
    "Specification": "规范",
    "Standard": "标准",
    "Convention": "约定",
    "Pattern": "模式",
    "Practice": "实践",
    "Experience": "经验",
    "Knowledge": "知识",
    "Understanding": "理解",
    "Learning": "学习",
    "Study": "研究",
    "Research": "研究",
    "Investigation": "调查",
    "Analysis": "分析",
    "Examination": "检查",
    "Inspection": "检验",
    "Evaluation": "评估",
    "Assessment": "评估",
    "Measurement": "测量",
    "Calculation": "计算",
    "Computation": "计算",
    "Estimation": "估算",
    "Approximation": "近似",
    "Prediction": "预测",
    "Forecast": "预测",
    "Projection": "预测",
    "Planning": "规划",
    "Scheduling": "调度",
    "Coordination": "协调",
    "Organization": "组织",
    "Management": "管理",
    "Administration": "管理",
    "Governance": "治理",
    "Oversight": "监督",
    "Monitoring": "监控",
    "Tracking": "跟踪",
    "Reporting": "报告",
    "Documentation": "文档",
    "Communication": "沟通",
    "Collaboration": "协作",
    "Cooperation": "合作",
    "Integration": "集成",
    "Connection": "连接",
    "Link": "链接",
    "Reference": "参考",
    "Relation": "关系",
    "Association": "关联",
    "Dependency": "依赖",
    "Interaction": "交互",
    "Interface": "接口",
    "API": "API",
    "System": "系统",
    "Platform": "平台",
    "Application": "应用",
    "Software": "软件",
    "Program": "程序",
    "Code": "代码",
    "Script": "脚本",
    "Command": "命令",
    "Instruction": "指令",
    "Operation": "操作",
    "Execution": "执行",
    "Performance": "性能",
    "Efficiency": "效率",
    "Effectiveness": "效果",
    "Quality": "质量",
    "Reliability": "可靠性",
    "Availability": "可用性",
    "Scalability": "可扩展性",
    "Flexibility": "灵活性",
    "Maintainability": "可维护性",
    "Usability": "可用性",
    "Accessibility": "可访问性",
    "Security": "安全性",
    "Privacy": "隐私",
    "Compliance": "合规",
    "Regulation": "法规",
    "Policy": "政策",
    "Standard": "标准",
    "Guideline": "指导",
    "Procedure": "程序",
    "Process": "流程",
    "Workflow": "工作流",
    "Methodology": "方法论",
    "Framework": "框架",
    "Architecture": "架构",
    "Design": "设计",
    "Implementation": "实现",
    "Deployment": "部署",
    "Operation": "运营",
    "Maintenance": "维护",
    "Support": "支持",
    "Service": "服务",
    "Product": "产品",
    "Solution": "解决方案",
    "Offering": "提供",
    "Capability": "能力",
    "Feature": "功能",
    "Function": "功能",
    "Characteristic": "特征",
    "Property": "属性",
    "Attribute": "属性",
    "Quality": "质量",
    "Metric": "指标",
    "Indicator": "指标",
    "Measure": "度量",
    "KPI": "KPI",
    "Target": "目标",
    "Goal": "目标",
    "Objective": "目标",
    "Aim": "目的",
    "Purpose": "目的",
    "Intent": "意图",
    "Scope": "范围",
    "Boundary": "边界",
    "Limit": "限制",
    "Constraint": "约束",
    "Requirement": "需求",
    "Need": "需求",
    "Want": "想要",
    "Desire": "期望",
    "Expectation": "期望",
    "Outcome": "结果",
    "Result": "结果",
    "Output": "输出",
    "Deliverable": "交付物",
    "Artifact": "制品",
    "Product": "产品",
    "Service": "服务",
    "Solution": "解决方案",
    "Value": "价值",
    "Benefit": "益处",
    "Advantage": "优势",
    "Strength": "优势",
    "Weakness": "劣势",
    "Opportunity": "机会",
    "Threat": "威胁",
    "Risk": "风险",
    "Issue": "问题",
    "Challenge": "挑战",
    "Problem": "问题",
    "Concern": "关注",
    "Consideration": "考虑",
    "Factor": "因素",
    "Element": "元素",
    "Component": "组件",
    "Part": "部分",
    "Piece": "部分",
    "Segment": "部分",
    "Section": "章节",
    "Chapter": "章节",
    "Module": "模块",
    "Unit": "单元",
    "Item": "项目",
    "Entity": "实体",
    "Object": "对象",
    "Instance": "实例",
    "Occurrence": "出现",
    "Event": "事件",
    "Activity": "活动",
    "Task": "任务",
    "Action": "动作",
    "Step": "步骤",
    "Phase": "阶段",
    "Stage": "阶段",
    "Milestone": "里程碑",
    "Deadline": "截止日期",
    "Timeline": "时间线",
    "Schedule": "进度表",
    "Plan": "计划",
    "Strategy": "策略",
    "Tactic": "战术",
    "Approach": "方法",
    "Method": "方法",
    "Technique": "技术",
    "Tool": "工具",
    "Instrument": "工具",
    "Equipment": "设备",
    "Resource": "资源",
    "Asset": "资产",
    "Capital": "资本",
    "Investment": "投资",
    "Funding": "资金",
    "Budget": "预算",
    "Cost": "成本",
    "Expense": "费用",
    "Price": "价格",
    "Rate": "比率",
    "Ratio": "比率",
    "Percentage": "百分比",
    "Proportion": "比例",
    "Share": "份额",
    "Portion": "部分",
    "Segment": "部分",
    "Market": "市场",
    "Industry": "行业",
    "Sector": "板块",
    "Niche": "细分",
    "Domain": "领域",
    "Field": "领域",
    "Area": "区域",
    "Space": "空间",
    "Environment": "环境",
    "Context": "上下文",
    "Background": "背景",
    "History": "历史",
    "Experience": "经验",
    "Expertise": "专业知识",
    "Knowledge": "知识",
    "Skill": "技能",
    "Ability": "能力",
    "Competence": "能力",
    "Proficiency": "熟练度",
    "Mastery": "精通",
    "Understanding": "理解",
    "Insight": "洞察",
    "Wisdom": "智慧",
    "Intelligence": "智能",
    "Information": "信息",
    "Data": "数据",
    "Content": "内容",
    "Material": "材料",
    "Resource": "资源",
    "Reference": "参考",
    "Source": "来源",
    "Origin": "源头",
    "Author": "作者",
    "Creator": "创建者",
    "Owner": "所有者",
    "User": "用户",
    "Customer": "客户",
    "Client": "客户",
    "Partner": "合作伙伴",
    "Vendor": "供应商",
    "Supplier": "供应商",
    "Provider": "提供商",
    "Stakeholder": "利益相关者",
    "Audience": "受众",
    "Reader": "读者",
    "Viewer": "观众",
    "Visitor": "访客",
    "Guest": "客人",
    "Member": "成员",
    "Participant": "参与者",
    "Contributor": "贡献者",
    "Maintainer": "维护者",
    "Developer": "开发者",
    "Engineer": "工程师",
    "Architect": "架构师",
    "Designer": "设计师",
    "Manager": "经理",
    "Director": "总监",
    "Executive": "高管",
    "Leader": "领导者",
    "Team": "团队",
    "Group": "组",
    "Organization": "组织",
    "Company": "公司",
    "Business": "业务",
    "Enterprise": "企业",
    "Corporation": "公司",
    "Institution": "机构",
    "Agency": "机构",
    "Government": "政府",
    "Public": "公众",
    "Private": "私营",
    "Personal": "个人",
    "Individual": "个人",
    "Professional": "专业",
    "Academic": "学术",
    "Technical": "技术",
    "Practical": "实践",
    "Theoretical": "理论",
    "Conceptual": "概念",
    "Abstract": "抽象",
    "Concrete": "具体",
    "Specific": "具体",
    "General": "一般",
    "Universal": "通用",
    "Global": "全球",
    "International": "国际",
    "Local": "本地",
    "Regional": "区域",
    "National": "国家",
    "Domestic": "国内",
    "Foreign": "国外",
    "External": "外部",
    "Internal": "内部",
    "Public": "公开",
    "Private": "私密",
    "Confidential": "机密",
    "Secret": "秘密",
    "Sensitive": "敏感",
    "Classified": "分类",
    "Restricted": "限制",
    "Protected": "保护",
    "Secure": "安全",
    "Safe": "安全",
    "Trusted": "可信",
    "Verified": "验证",
    "Authenticated": "认证",
    "Authorized": "授权",
    "Permitted": "允许",
    "Allowed": "允许",
    "Enabled": "启用",
    "Disabled": "禁用",
    "Blocked": "阻止",
    "Banned": "禁止",
    "Prohibited": "禁止",
    "Forbidden": "禁止",
    "Illegal": "非法",
    "Legitimate": "合法",
    "Valid": "有效",
    "Invalid": "无效",
    "Correct": "正确",
    "Incorrect": "不正确",
    "Right": "正确",
    "Wrong": "错误",
    "True": "真",
    "False": "假",
    "Yes": "是",
    "No": "否",
    "Maybe": "可能",
    "Perhaps": "或许",
    "Possibly": "可能",
    "Probably": "大概",
    "Likely": "可能",
    "Unlikely": "不太可能",
    "Certain": "确定",
    "Uncertain": "不确定",
    "Sure": "确定",
    "Unsure": "不确定",
    "Confident": "自信",
    "Doubtful": "怀疑",
    "Skeptical": "怀疑",
    "Optimistic": "乐观",
    "Pessimistic": "悲观",
    "Hopeful": "充满希望",
    "Fearful": "害怕",
    "Anxious": "焦虑",
    "Calm": "冷静",
    "Excited": "兴奋",
    "Bored": "无聊",
    "Interested": "感兴趣",
    "Curious": "好奇",
    "Eager": "渴望",
    "Reluctant": "不情愿",
    "Willing": "愿意",
    "Ready": "准备",
    "Prepared": "准备",
    "Available": "可用",
    "Unavailable": "不可用",
    "Busy": "忙",
    "Free": "空闲",
    "Open": "开放",
    "Closed": "关闭",
    "Active": "活跃",
    "Inactive": "不活跃",
    "Enabled": "启用",
    "Disabled": "禁用",
    "On": "开",
    "Off": "关",
    "Up": "上",
    "Down": "下",
    "Left": "左",
    "Right": "右",
    "Forward": "前进",
    "Backward": "后退",
    "In": "进",
    "Out": "出",
    "Through": "通过",
    "Across": "横跨",
    "Between": "之间",
    "Among": "之中",
    "Within": "之内",
    "Without": "之外",
    "Beyond": "超越",
    "Behind": "之后",
    "Before": "之前",
    "After": "之后",
    "During": "期间",
    "While": "当",
    "When": "当",
    "Where": "在哪里",
    "Why": "为什么",
    "How": "如何",
    "What": "什么",
    "Which": "哪个",
    "Who": "谁",
    "Whose": "谁的",
    "Whom": "谁",
    "This": "这个",
    "That": "那个",
    "These": "这些",
    "Those": "那些",
    "Here": "这里",
    "There": "那里",
    "Now": "现在",
    "Then": "那时",
    "Always": "总是",
    "Never": "从不",
    "Sometimes": "有时",
    "Often": "经常",
    "Rarely": "很少",
    "Usually": "通常",
    "Normally": "正常",
    "Regularly": "定期",
    "Frequently": "频繁",
    "Occasionally": "偶尔",
    "Seldom": "很少",
    "Hardly": "几乎不",
    "Scarcely": "几乎不",
    "Barely": "仅仅",
    "Almost": "几乎",
    "Nearly": "差不多",
    "Approximately": "大约",
    "Roughly": "大约",
    "About": "大约",
    "Around": "左右",
    "Precisely": "精确",
    "Exactly": "确切",
    "Specifically": "具体",
    "Particularly": "特别",
    "Especially": "尤其",
    "Mainly": "主要",
    "Mostly": "大多",
    "Chiefly": "主要",
    "Primarily": "主要",
    "Largely": "很大程度",
    "Most": "最",
    "More": "更多",
    "Less": "更少",
    "Least": "最少",
    "Best": "最好",
    "Better": "更好",
    "Worse": "更差",
    "Worst": "最差",
    "Good": "好",
    "Bad": "坏",
    "High": "高",
    "Low": "低",
    "Big": "大",
    "Small": "小",
    "Large": "大",
    "Tiny": "小",
    "Huge": "巨大",
    "Minute": "微小",
    "Long": "长",
    "Short": "短",
    "Tall": "高",
    "Wide": "宽",
    "Narrow": "窄",
    "Thick": "厚",
    "Thin": "薄",
    "Heavy": "重",
    "Light": "轻",
    "Dark": "暗",
    "Bright": "亮",
    "Hot": "热",
    "Cold": "冷",
    "Warm": "暖",
    "Cool": "凉",
    "Dry": "干",
    "Wet": "湿",
    "Hard": "硬",
    "Soft": "软",
    "Rough": "粗糙",
    "Smooth": "平滑",
    "Sharp": "锐利",
    "Dull": "钝",
    "Clean": "干净",
    "Dirty": "脏",
    "Fresh": "新鲜",
    "Stale": "陈旧",
    "New": "新",
    "Old": "旧",
    "Young": "年轻",
    "Fast": "快",
    "Slow": "慢",
    "Quick": "快",
    "Rapid": "快速",
    "Swift": "迅速",
    "Sudden": "突然",
    "Gradual": "逐渐",
    "Steady": "稳定",
    "Stable": "稳定",
    "Firm": "坚固",
    "Solid": "坚固",
    "Strong": "强",
    "Weak": "弱",
    "Powerful": "强大",
    "Powerless": "无力",
    "Intense": "强烈",
    "Mild": "温和",
    "Extreme": "极端",
    "Moderate": "适度",
    "Average": "平均",
    "Normal": "正常",
    "Typical": "典型",
    "Standard": "标准",
    "Regular": "常规",
    "Common": "普通",
    "Unusual": "异常",
    "Rare": "罕见",
    "Unique": "独特",
    "Special": "特殊",
    "Particular": "特定",
    "Specific": "具体",
    "General": "一般",
    "Broad": "宽泛",
    "Narrow": "狭窄",
    "Wide": "宽",
    "Simple": "简单",
    "Complex": "复杂",
    "Complicated": "复杂",
    "Easy": "容易",
    "Difficult": "困难",
    "Hard": "困难",
    "Challenging": "具有挑战性",
    "Demanding": "苛刻",
    "Stressful": "压力",
    "Relaxing": "轻松",
    "Comfortable": "舒适",
    "Pleasant": "愉快",
    "Enjoyable": "有趣",
    "Boring": "无聊",
    "Tedious": "单调",
    "Monotonous": "单调",
    "Repetitive": "重复",
    "Routine": "常规",
    "Creative": "创意",
    "Innovative": "创新",
    "Original": "原创",
    "Traditional": "传统",
    "Conventional": "传统",
    "Modern": "现代",
    "Contemporary": "当代",
    "Current": "当前",
    "Recent": "最近",
    "Latest": "最新",
    "Past": "过去",
    "Present": "现在",
    "Future": "未来",
    "History": "历史",
    "Development": "发展",
    "Progress": "进步",
    "Growth": "增长",
    "Improvement": "改进",
    "Decline": "下降",
    "Decrease": "减少",
    "Increase": "增加",
    "Rise": "上升",
    "Fall": "下降",
    "Drop": "下降",
    "Change": "变化",
    "Shift": "转移",
    "Move": "移动",
    "Transition": "过渡",
    "Transformation": "转型",
    "Evolution": "演化",
    "Revolution": "革命",
    "Innovation": "创新",
    "Invention": "发明",
    "Discovery": "发现",
    "Exploration": "探索",
    "Research": "研究",
    "Study": "研究",
    "Investigation": "调查",
    "Examination": "检查",
    "Analysis": "分析",
    "Evaluation": "评估",
    "Assessment": "评估",
    "Review": "审查",
    "Audit": "审计",
    "Inspection": "检查",
    "Test": "测试",
    "Trial": "试验",
    "Experiment": "实验",
    "Simulation": "模拟",
    "Demonstration": "演示",
    "Presentation": "演示",
    "Exhibition": "展览",
    "Show": "展示",
    "Display": "显示",
    "Illustration": "说明",
    "Example": "示例",
    "Sample": "样本",
    "Model": "模型",
    "Prototype": "原型",
    "Draft": "草稿",
    "Sketch": "草图",
    "Outline": "大纲",
    "Summary": "摘要",
    "Abstract": "摘要",
    "Introduction": "介绍",
    "Conclusion": "结论",
    "Recommendation": "建议",
    "Suggestion": "建议",
    "Proposal": "提案",
    "Idea": "想法",
    "Concept": "概念",
    "Theory": "理论",
    "Principle": "原则",
    "Rule": "规则",
    "Law": "法律",
    "Regulation": "法规",
    "Policy": "政策",
    "Standard": "标准",
    "Guideline": "指导",
    "Instruction": "说明",
    "Direction": "指示",
    "Command": "命令",
    "Order": "命令",
    "Request": "请求",
    "Demand": "要求",
    "Requirement": "需求",
    "Specification": "规范",
    "Criteria": "标准",
    "Condition": "条件",
    "Term": "条款",
    "Clause": "条款",
    "Provision": "规定",
    "Section": "部分",
    "Part": "部分",
    "Piece": "部分",
    "Bit": "部分",
    "Fragment": "碎片",
    "Segment": "部分",
    "Portion": "部分",
    "Share": "份额",
    "Percentage": "百分比",
    "Fraction": "分数",
    "Ratio": "比率",
    "Proportion": "比例",
    "Rate": "率",
    "Speed": "速度",
    "Velocity": "速度",
    "Acceleration": "加速度",
    "Momentum": "动量",
    "Force": "力量",
    "Energy": "能量",
    "Power": "力量",
    "Strength": "强度",
    "Capacity": "容量",
    "Volume": "体积",
    "Size": "大小",
    "Dimension": "维度",
    "Measurement": "测量",
    "Quantity": "数量",
    "Amount": "数量",
    "Number": "数字",
    "Count": "计数",
    "Total": "总计",
    "Sum": "总和",
    "Average": "平均",
    "Mean": "平均",
    "Median": "中位数",
    "Mode": "众数",
    "Range": "范围",
    "Scope": "范围",
    "Extent": "程度",
    "Degree": "度",
    "Level": "级别",
    "Grade": "等级",
    "Rank": "排名",
    "Status": "状态",
    "State": "状态",
    "Condition": "条件",
    "Situation": "情况",
    "Position": "位置",
    "Location": "地点",
    "Place": "地方",
    "Spot": "地点",
    "Site": "站点",
    "Area": "区域",
    "Region": "地区",
    "Zone": "区域",
    "District": "区域",
    "Territory": "领土",
    "Space": "空间",
    "Room": "房间",
    "Building": "建筑",
    "Structure": "结构",
    "Facility": "设施",
    "Equipment": "设备",
    "Tool": "工具",
    "Instrument": "器具",
    "Device": "设备",
    "Machine": "机器",
    "System": "系统",
    "Network": "网络",
    "Platform": "平台",
    "Environment": "环境",
    "Setting": "设置",
    "Context": "上下文",
    "Background": "背景",
    "Framework": "框架",
    "Foundation": "基础",
    "Basis": "基础",
    "Ground": "地面",
    "Support": "支持",
    "Base": "基础",
    "Core": "核心",
    "Center": "中心",
    "Middle": "中间",
    "Edge": "边缘",
    "Border": "边界",
    "Boundary": "边界",
    "Limit": "限制",
    "End": "结束",
    "Start": "开始",
    "Beginning": "开始",
    "Conclusion": "结束",
    "Completion": "完成",
    "Finish": "完成",
}

def translate_markdown_content(content):
    """
    翻译Markdown内容，保持格式不变
    """
    lines = content.split('\n')
    translated_lines = []
    in_code_block = False
    code_fence_char = None

    for line in lines:
        # 检测代码块
        if line.strip().startswith('```'):
            if not in_code_block:
                in_code_block = True
                code_fence_char = line.strip()[3]
            else:
                in_code_block = False
                code_fence_char = None
            translated_lines.append(line)
            continue

        # 代码块内容不翻译
        if in_code_block:
            translated_lines.append(line)
            continue

        # 行内代码不翻译
        if '`' in line:
            parts = line.split('`')
            translated_parts = []
            for i, part in enumerate(parts):
                if i % 2 == 0:  # 不是行内代码
                    translated_parts.append(translate_text(part))
                else:  # 是行内代码
                    translated_parts.append(part)
            translated_lines.append('`'.join(translated_parts))
            continue

        # 翻译普通文本
        translated_lines.append(translate_text(line))

    return '\n'.join(translated_lines)

def translate_text(text):
    """
    翻译文本，保留Markdown格式
    """
    if not text or not text.strip():
        return text

    result = text

    # 处理标题格式
    if result.strip().startswith('#'):
        prefix_count = len(result) - len(result.lstrip('#'))
        prefix = result[:prefix_count]
        content = result[prefix_count:].strip()
        return prefix + ' ' + translate_simple_text(content)

    # 处理列表格式
    if result.strip().startswith(('-', '*', '+')):
        marker = result.strip()[0]
        content = result.strip()[1:].strip()
        if content:
            return marker + ' ' + translate_simple_text(content)
        return result

    # 处理编号列表
    if result.strip() and result.strip()[0].isdigit() and '.' in result:
        parts = result.strip().split('.', 1)
        if len(parts) == 2:
            number = parts[0]
            content = parts[1].strip()
            if content:
                return number + '. ' + translate_simple_text(content)

    # 处理引用格式
    if result.strip().startswith('>'):
        content = result.strip()[1:].strip()
        return '> ' + translate_simple_text(content)

    # 普通文本
    return translate_simple_text(result)

def translate_simple_text(text):
    """
    简单文本翻译
    """
    if not text:
        return text

    result = text

    # 按照优先级处理翻译
    # 先处理长词组，再处理短语，最后处理单词
    sorted_terms = sorted(TRANSLATION_MAP.items(), key=lambda x: len(x[0]), reverse=True)

    for english, chinese in sorted_terms:
        # 使用正则表达式进行单词边界匹配
        import re
        pattern = r'\b' + re.escape(english) + r'\b'
        result = re.sub(pattern, chinese, result, flags=re.IGNORECASE)

    return result

def main():
    # 读取之前的翻译数据
    input_file = 'skill-translations.json'
    output_file = 'skill-translations-zh.js'

    with open(input_file, 'r', encoding='utf-8') as f:
        translations = json.load(f)

    # 创建中文翻译
    zh_translations = {}
    count = 0

    for skill_id, data in translations.items():
        original = data['original']
        translated = translate_markdown_content(original)
        zh_translations[skill_id] = translated
        count += 1
        print(f"✓ 翻译 {skill_id}: {len(original)} -> {len(translated)} 字符")

    # 保存为JavaScript文件
    js_content = "// 技能完整中文翻译数据\n"
    js_content += "var skillTranslationsZh = {\n"

    for skill_id, translation in zh_translations.items():
        escaped_translation = json.dumps(translation, ensure_ascii=False)
        js_content += f'    "{skill_id}": {escaped_translation},\n'

    js_content += "};\n"

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(js_content)

    print(f"\n✓ 翻译完成！共 {count} 个技能")
    print(f"✓ 中文翻译已保存到 {output_file}")
    print(f"✓ 文件大小: {len(js_content)} 字节")

if __name__ == "__main__":
    main()
